apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  #namespace: eks-log-to-cloudwatchlogs
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
          ports:
            - containerPort: 80