apiVersion: v1
kind: Service
metadata:
  name: lb
  #namespace: eks-log-to-cloudwatchlogs
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    app: nginx