apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: 'dev_cluster' # クラスター名
  http.server: 'On'
  http.port: '2020'
  read.head: 'Off'
  read.tail: 'On'
  logs.region: 'ap-northeast-1' # 作成するリージョン
