name: Lint and Terraform plan with OICD Provider
on:
#  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  lint:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive .
  
  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: [lint]
    if: always() && (needs.lint.result == 'success')
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: deploy-role-session
          role-duration-seconds: 1200

      - name: Initialize Terraform
#        run: |
#          cd terraform/${{ matrix.path }}
#          terraform init -input=false
        run: terraform init -lockfile=readonly

      - name: Plan Terraform
        id: plan
        continue-on-error: true
        run: terraform plan -input=false -no-color          

      - name: Post Plan to GitHub PR
        uses: mshick/add-pr-comment@v1
        with:
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ## plan
            ```
            ${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}
            ```         