name: Terraform plan with OICD Provider
on:
  workflow_dispatch:

#permissions:
#  id-token: write
#  contents: read

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Read .tool-versions
        run: echo "::set-output name=terraform-version::$(cat .tool-versions)"
        id: terraform-version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "${{ steps.terraform-version.outputs.terraform-version }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: deploy-role-session
          role-duration-seconds: 1200

      - name: Initialize Terraform
#        run: |
#          cd terraform/${{ matrix.path }}
#          terraform init -input=false
#        run: terraform init -lockfile=readonly
        run: terraform init -input=false

      - name: Plan Terraform
        id: plan
        continue-on-error: true
        run: terraform plan -input=false -no-color          

      - name: Post Plan to GitHub PR
        uses: mshick/add-pr-comment@v1
        with:
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ## plan
            ```
            ${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}
            ```         
